export type Language = 'en' | 'hi' | 'pa';

export type ScreenId =
  | 'language'
  | 'login'
  | 'verification'
  | 'home'
  | 'voice'
  | 'booking'
  | 'confirmation'
  | 'queue'
  | 'payment'
  | 'findmandi'
  | 'bookings';

export interface Booking {
  id: string;
  crop: string;
  quantity: string;
  mandi: string;
  date: string;
  time: string;
  token: string;
  status: 'confirmed' | 'in-queue' | 'procured' | 'paid' | 'cancelled';
}

export interface MandiResult {
  name: string;
  distance: string;
 queueLength: number;
 availableSlots: number;
 waitTime: string;
}

export const crops = [
  { name: 'Wheat', hi: 'गेहूं', pa: 'ਕਣਕ', icon: 'Wheat' },
  { name: 'Rice', hi: 'चावल', pa: 'ਚੌਲ', icon: 'Rice' },
  { name: 'Cotton', hi: 'कपास', pa: 'ਕਪਾਹ', icon: 'Cloud' },
  { name: 'Maize', hi: 'मक्का', pa: 'ਮੱਕੀ', icon: 'CircleDot' },
  { name: 'Mustard', hi: 'सरसों', pa: 'ਸਰ੍ਹੋਂ', icon: 'Flower' },
  { name: 'Sugarcane', hi: 'गन्ना', pa: 'ਗੰਨਾ', icon: 'Sprout' },
];

export const mandis = [
  { name: 'Khanna Mandi', distance: '5 km', wait: '2 hrs' },
  { name: 'Ludhiana Main Mandi', distance: '12 km', wait: '4 hrs' },
  { name: 'Samrala Mandi', distance: '18 km', wait: '1 hr' },
];

export const mandiResults: MandiResult[] = [
  { name: 'Khanna Mandi', distance: '5 km', queueLength: 12, availableSlots: 8, waitTime: '~45 min' },
  { name: 'Ludhiana Main Mandi', distance: '12 km', queueLength: 28, availableSlots: 3, waitTime: '~2 hrs' },
  { name: 'Samrala Mandi', distance: '18 km', queueLength: 5, availableSlots: 15, waitTime: '~20 min' },
];

export const slots = [
  { time: '08:00 AM', capacity: 45, available: true },
  { time: '09:00 AM', capacity: 50, available: true },
  { time: '10:00 AM', capacity: 50, available: false },
  { time: '11:00 AM', capacity: 45, available: true },
  { time: '12:00 PM', capacity: 30, available: true },
  { time: '02:00 PM', capacity: 50, available: true },
];

export const aiRecommendedSlot = '09:00 AM';

export const t = {
  en: {
    chooseLang: 'Choose Your Language',
    continue: 'Continue',
    login: 'Login',
    mobileNum: 'Mobile Number',
    sendOtp: 'Send OTP',
    enterOtp: 'Enter OTP',
    verify: 'Verify',
    aadhaar: 'Aadhaar Number',
    verifyAadhaar: 'Verify Aadhaar',
    voiceLogin: 'Voice Login',
    welcome: 'Welcome, Farmer',
    upcomingSlot: 'Upcoming Slot',
    queueStatus: 'Queue Status',
    paymentStatus: 'Payment Status',
    bookSlot: 'Book Slot',
    nearbyMandi: 'Nearby Mandi',
    help: 'Help',
    voiceAssistant: 'Voice Assistant',
    selectCrop: 'Select Crop',
    enterQty: 'Enter Quantity (kg)',
    chooseMandi: 'Choose Mandi',
    selectDate: 'Select Date',
    chooseSlot: 'Choose Available Slot',
    aiRecommended: 'AI Recommended',
    confirmBooking: 'Confirm Booking',
    tokenNo: 'Token Number',
    date: 'Date & Time',
    expWait: 'Expected Waiting Time',
    smsSent: 'SMS Confirmation Sent',
    currentToken: 'Current Token',
    myToken: 'My Token',
    peopleAhead: 'People Ahead',
    estWait: 'Estimated Waiting Time',
    voiceUpdate: 'Voice Update',
    procDetails: 'Procurement Details',
    amountPayable: 'Amount Payable',
    payTimeline: 'Payment Timeline',
    bankTransfer: 'Bank Transfer Status',
    offline: 'Offline Mode',
    online: 'Online',
    tapToSpeak: 'Tap to Speak',
    listening: 'Listening...',
    identityVerification: 'Identity Verification',
    aadhaarVerified: 'Aadhaar Verified',
    farmerName: 'Farmer Name',
    farmerIdLabel: 'Farmer ID',
    verified: 'Verified',
    farmerType: 'Farmer Type',
    landOwner: 'Land Owner',
    tenantFarmer: 'Tenant Farmer',
    selectState: 'Select State',
    selectDistrict: 'Select District',
    surveyKhasra: 'Survey / Khasra Number',
    verifyLandRecords: 'Verify Land Records',
    checkingLandRecords: 'Checking Land Records...',
    verifiedLandRecord: 'Verified Land Record',
    landholderName: 'Landholder Name',
    landArea: 'Land Area',
    selectedCropLabel: 'Selected Crop',
    yieldBenchmark: 'Yield Benchmark',
    maxProcurementQuota: 'Maximum Procurement Quota',
    remainingQuota: 'Remaining Quota',
    procurementRequest: 'Procurement Request Validation',
    requestedQuantity: 'Requested Procurement Quantity',
    quintals: 'Quintals',
    withinQuota: 'Within Allowed Quota',
    quotaExceeded: 'Quota Exceeded',
    maxAllowed: 'Maximum Allowed',
    tokenRequestDenied: 'Token Request Denied',
    quotaUtilized: 'Quota Utilized',
    uploadLeaseAgreement: 'Upload Lease Agreement',
    uploadPanchayatCert: 'Upload Panchayat Certificate',
    verifyTenant: 'Verify Tenant Allocation',
    tenantVerified: 'Tenant Verified',
    parcel: 'Parcel',
    leasedArea: 'Leased Area',
    quotaLockedTo: 'Quota Locked to Tenant ID',
    parcelProtected: 'Parcel Protected From Duplicate Registration',
    duplicateParcelCheck: 'Duplicate Parcel Check',
    fraudRiskScore: 'Fraud Risk Score',
    seasonQuotaStatus: 'Season Quota Status',
    noDuplicateClaims: 'No Duplicate Claims Found',
    proceedToBooking: 'Proceed To Slot Booking',
    verificationCompleted: 'Verification completed. Smart scheduling available.',
    lowRisk: 'Low Risk',
    quotaAvailable: 'Quota Available',
    dashboard: 'Dashboard',
    farmerId: 'FRM-2045',
    switchLang: 'Switch Language',
    upcomingBooking: 'Upcoming Booking',
    lastProcurement: 'Last Procurement',
    amountPending: 'Amount Pending',
    amountPaid: 'Amount Paid',
    quickActions: 'Quick Actions',
    findMandis: 'Find Nearby Mandis',
    bookingHistory: 'Booking History',
    helpCenter: 'Help Center',
    payments: 'Payments',
    enterPincode: 'Enter Pincode',
    pincodePlaceholder: 'e.g. 141001',
    searchMandis: 'Search Mandis',
    nearbyCentres: 'Nearby Procurement Centres',
    currentQueue: 'Current Queue',
    availableSlotsToday: 'Available Slots Today',
    viewDetails: 'View Details',
    bookSlotBtn: 'Book Slot',
    noMandisFound: 'No mandis found for this pincode',
    myBookings: 'My Bookings',
    bookingId: 'Booking ID',
    viewQr: 'View QR Code',
    cancelBooking: 'Cancel Booking',
    cancelNotAllowed: 'Cannot cancel - procurement in progress',
    qrStorage: 'Your QR token is safely stored in Booking History.',
    openQr: 'Open QR',
    reDownloadQr: 'Re-download QR',
    shareQrSms: 'Share QR via SMS',
    downloadQr: 'Download QR',
    viewBooking: 'View Booking',
    bookingSuccessful: 'Booking Successful',
    generateToken: 'Generate Token',
    expectedQuantity: 'Expected Quantity',
    preferredDate: 'Preferred Date',
    availableTimeSlots: 'Available Time Slots',
    selectedMandi: 'Selected Mandi',
    cropType: 'Crop Type',
    noBookingsYet: 'No bookings yet',
    startBooking: 'Start Booking',
    active: 'Active',
    cancelled: 'Cancelled',
    confirmed: 'Confirmed',
    inQueue: 'In Queue',
    procured: 'Procured',
    paid: 'Paid',
  },
  hi: {
    chooseLang: 'अपनी भाषा चुनें',
    continue: 'आगे बढ़ें',
    login: 'लॉगिन',
    mobileNum: 'मोबाइल नंबर',
    sendOtp: 'OTP भेजें',
    enterOtp: 'OTP दर्ज करें',
    verify: 'सत्यापित करें',
    aadhaar: 'आधार नंबर',
    verifyAadhaar: 'आधार सत्यापित करें',
    voiceLogin: 'वॉइस लॉगिन',
    welcome: 'स्वागत है, किसान',
    upcomingSlot: 'आगामी स्लॉट',
    queueStatus: 'कतार स्थिति',
    paymentStatus: 'भुगतान स्थिति',
    bookSlot: 'स्लॉट बुक करें',
    nearbyMandi: 'नजदीकी मंडी',
    help: 'सहायता',
    voiceAssistant: 'वॉइस असिस्टेंट',
    selectCrop: 'फसल चुनें',
    enterQty: 'मात्रा दर्ज करें (किग्रा)',
    chooseMandi: 'मंडी चुनें',
    selectDate: 'तारीख चुनें',
    chooseSlot: 'उपलब्ध स्लॉट चुनें',
    aiRecommended: 'एआई अनुशंसित',
    confirmBooking: 'बुकिंग की पुष्टि करें',
    tokenNo: 'टोकन नंबर',
    date: 'तारीख और समय',
    expWait: 'अनुमानित प्रतीक्षा समय',
    smsSent: 'एसएमएस पुष्टिकरण भेजा गया',
    currentToken: 'वर्तमान टोकन',
    myToken: 'मेरा टोकन',
    peopleAhead: 'आगे लोग',
    estWait: 'अनुमानित प्रतीक्षा समय',
    voiceUpdate: 'वॉइस अपडेट',
    procDetails: 'खरीद विवरण',
    amountPayable: 'देय राशि',
    payTimeline: 'भुगतान समयरेखा',
    bankTransfer: 'बैंक ट्रांसफर स्थिति',
    offline: 'ऑफलाइन मोड',
    online: 'ऑनलाइन',
    tapToSpeak: 'बोलने के लिए टैप करें',
    listening: 'सुन रहा हूं...',
    identityVerification: 'पहचान सत्यापन',
    aadhaarVerified: 'आधार सत्यापित',
    farmerName: 'किसान का नाम',
    farmerIdLabel: 'किसान आईडी',
    verified: 'सत्यापित',
    farmerType: 'किसान प्रकार',
    landOwner: 'भूमि स्वामी',
    tenantFarmer: 'पट्टा किसान',
    selectState: 'राज्य चुनें',
    selectDistrict: 'जिला चुनें',
    surveyKhasra: 'सर्वे / खसरा नंबर',
    verifyLandRecords: 'भूमि रिकॉर्ड सत्यापित करें',
    checkingLandRecords: 'भूमि रिकॉर्ड जांचे जा रहे हैं...',
    verifiedLandRecord: 'सत्यापित भूमि रिकॉर्ड',
    landholderName: 'भूमि स्वामी का नाम',
    landArea: 'भूमि क्षेत्रफल',
    selectedCropLabel: 'चयनित फसल',
    yieldBenchmark: 'उपज मानक',
    maxProcurementQuota: 'अधिकतम खरीद कोटा',
    remainingQuota: 'शेष कोटा',
    procurementRequest: 'खरीद अनुरोध सत्यापन',
    requestedQuantity: 'अनुरोधित खरीद मात्रा',
    quintals: 'क्विंटल',
    withinQuota: 'अनुमत कोटा के भीतर',
    quotaExceeded: 'कोटा सीमा से अधिक',
    maxAllowed: 'अधिकतम अनुमत',
    tokenRequestDenied: 'टोकन अनुरोध अस्वीकृत',
    quotaUtilized: 'कोटा का उपयोग',
    uploadLeaseAgreement: 'पट्टा समझौता अपलोड करें',
    uploadPanchayatCert: 'पंचायत प्रमाणपत्र अपलोड करें',
    verifyTenant: 'पट्टा आवंटन सत्यापित करें',
    tenantVerified: 'पट्टा सत्यापित',
    parcel: 'पार्सल',
    leasedArea: 'पट्टे का क्षेत्रफल',
    quotaLockedTo: 'कोटा पट्टा आईडी पर लॉक',
    parcelProtected: 'पार्सल डुप्लिकेट पंजीकरण से सुरक्षित',
    duplicateParcelCheck: 'डुप्लिकेट पार्सल जांच',
    fraudRiskScore: 'धोखाधड़ी जोखिम स्कोर',
    seasonQuotaStatus: 'सीजन कोटा स्थिति',
    noDuplicateClaims: 'कोई डुप्लिकेट दावा नहीं मिला',
    proceedToBooking: 'स्लॉट बुकिंग के लिए आगे बढ़ें',
    verificationCompleted: 'सत्यापन पूर्ण। स्मार्ट शेड्यूलिंग उपलब्ध।',
    lowRisk: 'कम जोखिम',
    quotaAvailable: 'कोटा उपलब्ध',
    dashboard: 'डैशबोर्ड',
    farmerId: 'FRM-2045',
    switchLang: 'भाषा बदलें',
    upcomingBooking: 'आगामी बुकिंग',
    lastProcurement: 'अंतिम खरीद',
    amountPending: 'देय राशि',
    amountPaid: 'भुगतान राशि',
    quickActions: 'त्वरित क्रियाएं',
    findMandis: 'नजदीकी मंडी खोजें',
    bookingHistory: 'बुकिंग इतिहास',
    helpCenter: 'सहायता केंद्र',
    payments: 'भुगतान',
    enterPincode: 'पिनकोड दर्ज करें',
    pincodePlaceholder: 'जैसे 141001',
    searchMandis: 'मंडी खोजें',
    nearbyCentres: 'नजदीकी खरीद केंद्र',
    currentQueue: 'वर्तमान कतार',
    availableSlotsToday: 'आज उपलब्ध स्लॉट',
    viewDetails: 'विवरण देखें',
    bookSlotBtn: 'स्लॉट बुक करें',
    noMandisFound: 'इस पिनकोड के लिए कोई मंडी नहीं मिली',
    myBookings: 'मेरी बुकिंग',
    bookingId: 'बुकिंग आईडी',
    viewQr: 'क्यूआर कोड देखें',
    cancelBooking: 'बुकिंग रद्द करें',
    cancelNotAllowed: 'रद्द नहीं कर सकते - खरीद चल रही है',
    qrStorage: 'आपका क्यूआर टोकन बुकिंग इतिहास में सुरक्षित है।',
    openQr: 'क्यूआर खोलें',
    reDownloadQr: 'क्यूआर फिर से डाउनलोड करें',
    shareQrSms: 'एसएमएस से क्यूआर साझा करें',
    downloadQr: 'क्यूआर डाउनलोड करें',
    viewBooking: 'बुकिंग देखें',
    bookingSuccessful: 'बुकिंग सफल',
    generateToken: 'टोकन जनरेट करें',
    expectedQuantity: 'अनुमानित मात्रा',
    preferredDate: 'पसंदीदा तारीख',
    availableTimeSlots: 'उपलब्ध समय स्लॉट',
    selectedMandi: 'चयनित मंडी',
    cropType: 'फसल प्रकार',
    noBookingsYet: 'अभी तक कोई बुकिंग नहीं',
    startBooking: 'बुकिंग शुरू करें',
    active: 'सक्रिय',
    cancelled: 'रद्द',
    confirmed: 'पुष्टि',
    inQueue: 'कतार में',
    procured: 'खरीदा',
    paid: 'भुगतान',
  },
  pa: {
    chooseLang: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    continue: 'ਅੱਗੇ ਵਧੋ',
    login: 'ਲਾਗਇਨ',
    mobileNum: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    sendOtp: 'OTP ਭੇਜੋ',
    enterOtp: 'OTP ਦਰਜ ਕਰੋ',
    verify: 'ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    aadhaar: 'ਆਧਾਰ ਨੰਬਰ',
    verifyAadhaar: 'ਆਧਾਰ ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    voiceLogin: 'ਵਾਇਸ ਲਾਗਇਨ',
    welcome: 'ਜੀ ਆਇਆਨੂੰ, ਕਿਸਾਨ',
    upcomingSlot: 'ਅਗਲਾ ਸਲਾਟ',
    queueStatus: 'ਕਤਾਰ ਸਥਿਤੀ',
    paymentStatus: 'ਭੁਗਤਾਨ ਸਥਿਤੀ',
    bookSlot: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    nearbyMandi: 'ਨੇੜਲੀ ਮੰਡੀ',
    help: 'ਮਦਦ',
    voiceAssistant: 'ਵਾਇਸ ਅਸਿਸਟੈਂਟ',
    selectCrop: 'ਫਸਲ ਚੁਣੋ',
    enterQty: 'ਮਾਤਰਾ ਦਰਜ ਕਰੋ (ਕਿਲੋ)',
    chooseMandi: 'ਮੰਡੀ ਚੁਣੋ',
    selectDate: 'ਮਿਤੀ ਚੁਣੋ',
    chooseSlot: 'ਉਪਲਬਧ ਸਲਾਟ ਚੁਣੋ',
    aiRecommended: 'ਏਆਈ ਸਿਫਾਰਸ਼ੀ',
    confirmBooking: 'ਬੁਕਿੰਗ ਪੁਸ਼ਟੀ ਕਰੋ',
    tokenNo: 'ਟੋਕਨ ਨੰਬਰ',
    date: 'ਮਿਤੀ ਅਤੇ ਸਮਾਂ',
    expWait: 'ਅਨੁਮਾਨਿਤ ਉਡੀਕ ਸਮਾਂ',
    smsSent: 'ਐਸਐਮਐਸ ਪੁਸ਼ਟੀ ਭੇਜੀ',
    currentToken: 'ਮੌਜੂਦਾ ਟੋਕਨ',
    myToken: 'ਮੇਰਾ ਟੋਕਨ',
    peopleAhead: 'ਅੱਗੇ ਲੋਕ',
    estWait: 'ਅਨੁਮਾਨਿਤ ਉਡੀਕ ਸਮਾਂ',
    voiceUpdate: 'ਵਾਇਸ ਅਪਡੇਟ',
    procDetails: 'ਖਰੀਦ ਵੇਰਵਾ',
    amountPayable: 'ਦੇਣਯੋਗ ਰਕਮ',
    payTimeline: 'ਭੁਗਤਾਨ ਸਮਾਂ-ਰੇਖਾ',
    bankTransfer: 'ਬੈਂਕ ਟ੍ਰਾਂਸਫਰ ਸਥਿਤੀ',
    offline: 'ਆਫਲਾਈਨ ਮੋਡ',
    online: 'ਆਨਲਾਈਨ',
    tapToSpeak: 'ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
    identityVerification: 'ਪਛਾਣ ਪ੍ਰਮਾਣਿਕਤਾ',
    aadhaarVerified: 'ਆਧਾਰ ਪ੍ਰਮਾਣਿਤ',
    farmerName: 'ਕਿਸਾਨ ਦਾ ਨਾਂ',
    farmerIdLabel: 'ਕਿਸਾਨ ਆਈਡੀ',
    verified: 'ਪ੍ਰਮਾਣਿਤ',
    farmerType: 'ਕਿਸਾਨ ਕਿਸਮ',
    landOwner: 'ਜ਼ਮੀਨ ਮਾਲਕ',
    tenantFarmer: 'ਪਟਤੇਦਾਰ ਕਿਸਾਨ',
    selectState: 'ਰਾਜ ਚੁਣੋ',
    selectDistrict: 'ਜ਼ਿਲਾ ਚੁਣੋ',
    surveyKhasra: 'ਸਰਵੇ / ਖਸਰਾ ਨੰਬਰ',
    verifyLandRecords: 'ਜ਼ਮੀਨ ਰਿਕਾਰਡ ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    checkingLandRecords: 'ਜ਼ਮੀਨ ਰਿਕਾਰਡ ਜਾਂਚੇ ਜਾ ਰਹੇ ਹਨ...',
    verifiedLandRecord: 'ਪ੍ਰਮਾਣਿਤ ਜ਼ਮੀਨ ਰਿਕਾਰਡ',
    landholderName: 'ਜ਼ਮੀਨ ਮਾਲਕ ਦਾ ਨਾਂ',
    landArea: 'ਜ਼ਮੀਨ ਖੇਤਰਫਲ',
    selectedCropLabel: 'ਚੁਣੀ ਫਸਲ',
    yieldBenchmark: 'ਝਾਤ ਮਾਪਦੰਡ',
    maxProcurementQuota: 'ਵੱਧ ਤੋਂ ਵੱਧ ਖਰੀਦ ਕੋਟਾ',
    remainingQuota: 'ਬਾਕੀ ਕੋਟਾ',
    procurementRequest: 'ਖਰੀਦ ਬੇਨਤੀ ਪ੍ਰਮਾਣਿਕਤਾ',
    requestedQuantity: 'ਬੇਨਤੀ ਖਰੀਦ ਮਾਤਰਾ',
    quintals: 'ਕੁਇੰਟਲ',
    withinQuota: 'ਮਨਜ਼ੁਦ ਕੋਟੇ ਅੰਦਰ',
    quotaExceeded: 'ਕੋਟਾ ਸੀਮਾ ਤੋਂ ਵੱਧ',
    maxAllowed: 'ਵੱਧ ਤੋਂ ਵੱਧ ਮਨਜ਼ੁਦ',
    tokenRequestDenied: 'ਟੋਕਨ ਬੇਨਤੀ ਰੱਦ',
    quotaUtilized: 'ਕੋਟਾ ਵਰਤਿਆ',
    uploadLeaseAgreement: 'ਪਟਤਾ ਸਮਝੌਤਾ ਅੱਪਲੋਡ ਕਰੋ',
    uploadPanchayatCert: 'ਪੰਚਾਇਤ ਸਰਟੀਫਿਕੇਟ ਅੱਪਲੋਡ ਕਰੋ',
    verifyTenant: 'ਪਟਤੇਦਾਰ ਵੰਡ ਪ੍ਰਮਾਣਿਤ ਕਰੋ',
    tenantVerified: 'ਪਟਤੇਦਾਰ ਪ੍ਰਮਾਣਿਤ',
    parcel: 'ਪਾਰਸਲ',
    leasedArea: 'ਪਟਤੇ ਦਾ ਖੇਤਰਫਲ',
    quotaLockedTo: 'ਕੋਟਾ ਪਟਤੇਦਾਰ ਆਈਡੀ ਤੇ ਲਾਕ',
    parcelProtected: 'ਪਾਰਸਲ ਡੁਪਲੀਕੇਟ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਤੋਂ ਸੁਰੱਖਿਅਤ',
    duplicateParcelCheck: 'ਡੁਪਲੀਕੇਟ ਪਾਰਸਲ ਜਾਂਚ',
    fraudRiskScore: 'ਧੋਖਾਧੜੀ ਜੋਖਮ ਸਕੋਰ',
    seasonQuotaStatus: 'ਸੀਜ਼ਨ ਕੋਟਾ ਸਥਿਤੀ',
    noDuplicateClaims: 'ਕੋਈ ਡੁਪਲੀਕੇਟ ਦਾਅਵਾ ਨਹੀਂ ਮਿਲਿਆ',
    proceedToBooking: 'ਸਲਾਟ ਬੁਕਿੰਗ ਲਈ ਅੱਗੇ ਵਧੋ',
    verificationCompleted: 'ਪ੍ਰਮਾਣਿਕਤਾ ਪੂਰੀ। ਸਮਾਰਟ ਸ਼ਡਿਊਲਿੰਗ ਉਪਲਬਧ।',
    lowRisk: 'ਘੱਟ ਜੋਖਮ',
    quotaAvailable: 'ਕੋਟਾ ਉਪਲਬਧ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    farmerId: 'FRM-2045',
    switchLang: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    upcomingBooking: 'ਅਗਲੀ ਬੁਕਿੰਗ',
    lastProcurement: 'ਆਖਰੀ ਖਰੀਦ',
    amountPending: 'ਬਕਾਇਆ ਰਕਮ',
    amountPaid: 'ਭੁਗਤਾਨ ਰਕਮ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    findMandis: 'ਨੇੜਲੀਆਂ ਮੰਡੀਆਂ ਲੱਭੋ',
    bookingHistory: 'ਬੁਕਿੰਗ ਅਤੀਤ',
    helpCenter: 'ਮਦਦ ਕੇਂਦਰ',
    payments: 'ਭੁਗਤਾਨ',
    enterPincode: 'ਪਿੰਨਕੋਡ ਦਰਜ ਕਰੋ',
    pincodePlaceholder: 'ਜਿਵੇਂ 141001',
    searchMandis: 'ਮੰਡੀਆਂ ਲੱਭੋ',
    nearbyCentres: 'ਨੇੜਲੇ ਖਰੀਦ ਕੇਂਦਰ',
    currentQueue: 'ਮੌਜੂਦਾ ਕਤਾਰ',
    availableSlotsToday: 'ਅੱਜ ਉਪਲਬਧ ਸਲਾਟ',
    viewDetails: 'ਵੇਰਵਾ ਵੇਖੋ',
    bookSlotBtn: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    noMandisFound: 'ਇਸ ਪਿੰਨਕੋਡ ਲਈ ਕੋਈ ਮੰਡੀ ਨਹੀਂ ਮਿਲੀ',
    myBookings: 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    bookingId: 'ਬੁਕਿੰਗ ਆਈਡੀ',
    viewQr: 'ਕਿਉਰ ਕੋਡ ਵੇਖੋ',
    cancelBooking: 'ਬੁਕਿੰਗ ਰੱਦ ਕਰੋ',
    cancelNotAllowed: 'ਰੱਦ ਨਹੀਂ ਕਰ ਸਕਦੇ - ਖਰੀਦ ਚੱਲ ਰਹੀ ਹੈ',
    qrStorage: 'ਤੁਹਾਡਾ ਕਿਉਰ ਟੋਕਨ ਬੁਕਿੰਗ ਅਤੀਤ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਹੈ।',
    openQr: 'ਕਿਉਰ ਖੋਲ੍ਹੋ',
    reDownloadQr: 'ਕਿਉਰ ਮੁੜ ਡਾਊਨਲੋਡ ਕਰੋ',
    shareQrSms: 'ਐਸਐਮਐਸ ਰਾਹੀਂ ਕਿਉਰ ਸਾਂਝਾ ਕਰੋ',
    downloadQr: 'ਕਿਉਰ ਡਾਊਨਲੋਡ ਕਰੋ',
    viewBooking: 'ਬੁਕਿੰਗ ਵੇਖੋ',
    bookingSuccessful: 'ਬੁਕਿੰਗ ਸਫਲ',
    generateToken: 'ਟੋਕਨ ਬਣਾਓ',
    expectedQuantity: 'ਅਨੁਮਾਨਿਤ ਮਾਤਰਾ',
    preferredDate: 'ਪਸੰਦੀਦਾ ਮਿਤੀ',
    availableTimeSlots: 'ਉਪਲਬਧ ਸਮਾਂ ਸਲਾਟ',
    selectedMandi: 'ਚੁਣੀ ਮੰਡੀ',
    cropType: 'ਫਸਲ ਕਿਸਮ',
    noBookingsYet: 'ਅਜੇ ਤੱਕ ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ',
    startBooking: 'ਬੁਕਿੰਗ ਸ਼ੁਰੂ ਕਰੋ',
    active: 'ਸਰਗਰਮ',
    cancelled: 'ਰੱਦ',
    confirmed: 'ਪੁਸ਼ਟੀ',
    inQueue: 'ਕਤਾਰ ਵਿੱਚ',
    procured: 'ਖਰੀਦਿਆ',
    paid: 'ਭੁਗਤਾਨ',
  },
};

export type Lang = typeof t.en;
